[package]
name = "kv-client"
version = "0.1.0"
edition = "2021"

[dependencies]
kv-common = { path = "../kv-common" }
log = "0.4"
clap = { version = "4.5.30", features = ["derive"] }
winapi = { version = "0.3", features = ["wincon", "consoleapi"] }
