[package]
name = "kv-client"
version = "0.1.0"
edition = "2021"

[dependencies]
kv-common = { path = "../kv-common" }
log = "0.4"
simplelog = "0.12"
config = "0.13"
clap = "2.33"
winapi = { version = "0.3", features = ["wincon", "consoleapi"] }