[package]
name = "kv-server"
version = "0.1.0"
edition = "2021"

[dependencies]
kv-common = { path = "../kv-common" }
log = "0.4"
simplelog = "0.12"
chrono = "0.4"
config = "0.13"
clap = "2.33"
ctrlc = "3.2"