[server]
# 服务器监听端口
port = 6379
# 服务器IP地址
host = "127.0.0.1"

[persistence]
# 数据持久化文件路径
data_file = "data/storage.dat"
# 持久化方式: "none", "on_change", "interval"
mode = "on_change"
# 定时持久化的时间间隔(秒)，仅当mode为interval时有效
interval_seconds = 300

[storage]
# 是否启用键过期功能
enable_expiry = true
# 默认键过期时间(秒)，-1表示永不过期
default_expiry_seconds = 3600

[memory]
# 是否启用内存优化
enable_memory_optimization = true
# 低频检查时间间隔(秒)
low_frequency_check_interval = 60
# 访问次数阈值
access_threshold = 100
# 闲置时间阈值(秒)
idle_time_threshold = 600
# 内存中保留的最大键数
max_memory_keys = 1000

[logging]
# 日志文件路径
log_file = "logs/server.log"
# 日志级别: "error", "warn", "info", "debug", "trace"
level = "info"
